name: Update ArtStation JSON

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours at minute 0
  workflow_dispatch: {}        #Also allow manual “Run workflow” from the Actions tab

permissions:
  contents: write              #Only grant repo-contents write (for git push)

jobs:
  build:
    runs-on: ubuntu-latest     #Use the latest Ubuntu runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        #Pulls down code so subsequent steps can read/write files

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        # Ensures `node` and `npm` are available

      - name: Install dependencies
        run: npm install node-fetch@2
        # Installs only the fetch library needed for our script

      - name: Fetch ArtStation data
        run: node scripts/fetchArtstation.js wiirus
        #Runs custom script to hit ArtStation’s JSON endpoint,
        #aggregate all pages, and output `data/artworks.json`

      - name: Commit & push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/artworks.json
          git diff --quiet || git commit -m "chore: update ArtStation artworks"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #Uses the built-in token to authenticate,
        #commits only if there are changes, and pushes back to repo
